### ISSUE TITLE
Simulation checklist

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#269]
We need to finalize the configuration of the simulation.

### AMMPS
- [ ] Double check that config parameters are 'what we want' -- agree with SHARKFin. - @mesalas 
- [ ] Make sure we are using the most recent binaries. - @mesalas @wjt5121 

### SHARKFin
- [ ] Make sure the Lucas0 population is configured how we want - @alanlujan91 @sbenthall 
- [ ] Make sure the starting wealth of the Lucas0 population is calculated accurately - @alanlujan91 @sbenthall 
- [ ] Make sure that the starting expectations and preferences are valid, given the LAP constraint. - @alanlujan91 @sbenthall 

### Assumptions

- Initial price is 100 dollars.
- Initial dividend is computed as a function of the price, and LAP logic.
- Infinite horizon consumers.

**Comment by sbenthall** [comment]
Sorry for the confusion.

@alanlujan91 and I met yesterday and agreed:
- Alan is the parameter czar, responsible for choosing the consumer and economic system parameters for SHARKFin
- The place where the canonical values for these parameters will be kept will be this wiki page, unless he says otherwise: https://github.com/sbenthall/SHARKFin/wiki/JEBO-Parameters

I can take responsibility for getting the correct parameters into the SHARKFin configuration via the CLI.

I'm not sure I'm following what you're saying about doing a run with less dividend stdev. Let's discuss soon.

**Comment by mesalas** [comment]
I think we should also add to the check list that we should double check commands that Bills scripts use to call `ammps_config_generator`, `ammps` and `SHARKfin`.
